# Generated by Django 2.2.3 on 2020-04-24 16:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='File', max_length=256, null=True)),
                ('usage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('language', models.CharField(default='File', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='repoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=256)),
                ('language', models.CharField(default='File', max_length=256, null=True)),
                ('description', models.TextField(default='Missing description')),
                ('link', models.TextField(default='#')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='projectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='project_images')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySite.Project')),
            ],
        ),
        migrations.CreateModel(
            name='contributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribName', models.CharField(default='Anon', max_length=64)),
                ('commits', models.CharField(default='0', max_length=64)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySite.repoContent')),
            ],
        ),
    ]
