# Generated by Django 2.2.3 on 2020-04-18 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repocontent',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='repocontent',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
