# Generated by Django 2.2.3 on 2020-04-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='File', max_length=256, null=True)),
                ('usage', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='contributors',
            name='commits',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
