# Generated by Django 2.2.3 on 2020-04-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(default='File', max_length=64),
        ),
    ]
